### ISSUE TITLE
[Wiki] Documenter l'intégration d'un membre au projet

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#1]
Créer une page dans le Wiki qui détaille les différentes actions à effectuer pour intégrer le projet (s'inspirer éventuellement du mail de Rossi ci-dessous).
###### Mail de Rossi

Il faudrait installer votre environnement de développement :
1. Rejoindre la mailing liste : https://groups.google.com/forum/?fromgroups#!forum/jcertif-backend-2013, s'abonner de tel sorte à recevoir tous les emails à chaque fois et prévenez Rossi que c'est OK
2. Ouvrir un compte chez github (https://github.com/)
3. Ajouter une photo chez gravatar (https://en.gravatar.com/site/login) avec la même adresse email que celle utilisée pour github
4. Communiquer le nom de son profil github pour que Rossi puisse créer les droits  sur le projet Github
5. Installer Git sur son poste (pour windows http://msysgit.github.com/)
6. Ajouter le plugin Git dans vos IDE préférés (egit pour Eclipse)
7. Télécharger la version 2.0.4 de playframework, dezipper puis ajouter le répertoire dans votre PATH. Objectif = avoir accès à la commande "play" partout
8. Récupérer les sources du projet Github avec la commande "git clone https://github.com/JCERTIFLab/jcertif-backend-2013.git" ou via le menu de votre IDE. Il n'y a pas grand chose pour le moment, j'ai juste générer le projet avec "play new"
9. Tester un commit sur github (attendre que je vous donne le go quand les droits sont OK)

> Modifier un fichier
> git add .
> git commit -m "Test de commit"
> git push
> 10. Faire le tutoriel Play Framework pour Java : http://www.playframework.org/documentation/2.0.4/JavaTodoList
> 11. Installer mongodb sur son poste : http://www.mongodb.org/

**Comment by lefuturis** [comment]
le status du projet c cmt?

**Comment by bigoliver** [comment]
ça avance bien...

2013/2/18 lefuturis notifications@github.com

> le status du projet c cmt?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JCERTIFLab/jcertif-backend-2013/issues/1#issuecomment-13744558.

## 
- Olivier
