### ISSUE TITLE
[Service] Liste des présentateurs

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#10]
Créer un service REST : 

Requête : GET  /speaker/list       

Réponse : HTTP 200 : liste d'objet Speaker au format JSON.
Exemple : {{email : 'bill@jcertif.org', lastname : 'Gates'},{email : 'douglas@objis.com', lastname : 'Mbiandou'}}

**Comment by bigoliver** [comment]
Done
