### ISSUE TITLE
[Service] Inscrire un présentateur

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#11]
Créer un service REST :
Requête : POST /speaker/register   un objet Speaker au format JSON.
Exemple : {email : 'lab@jcertif.org', lastname : 'Gates', fistname : 'Bill' }
Veuillez à valoriser tous les champs obligatoires.

Réponse : HTTP 200

**Comment by bigoliver** [comment]
Done
