### ISSUE TITLE
[Design] Utilisation d'un plugin Play pour la persistance du model

### ISSUE THREAD

**Issue by martialsomda** [JCERTIFLab/jcertif-backend-2013#112]
Rendre plus transparent le mécanisme de persistance (soit utiliser l'existant en écrivant un plugin custom chargé de la persistance des objets du model, soit en utilisant un plugin déjà existant tel Morphia)

**Comment by roddet** [comment]
Tu as évoqué 2 pistes.
Privilégies-tu déjà une ?

**Comment by martialsomda** [comment]
J'ai une préférence pour morphia..Morphia nous apportera la robustesse d'une librairie déjà éprouvée.
Créer un plugin custom peut être sympa mais difficile à mettre en place. Par ce que ce qu'il y a derrière la notion de plugin ici c'est en fait un framework de mapping Objet Java -> mongoDB.
Pour vraiment masquer le mécanisme de persistance, il faudrait que sur les objet du model, lorsqu'on invoque la méthode save() par example, que ça déclenche un évènement qui serait intercepté par le moteur de persistance qui saurait traduire les annotations sur l'objet en requête pour mongo => bref, re développer un petit morphia.
Cette issue pour moi n'est plus très prioritaire par qu'au final, avec la vague de refactoring sur le model je trouve qu'on est pas si mal que ça..ça serai plus beau encore avec morphia mais globalement le code n'est pas trop complexe dans l'état..qu'en penses tu?

**Comment by roddet** [comment]
Oui ce point n'est pas prioritaire, on pourra y revenir plus tard en faisant une analyse plus fine du gain que pourrait nous apporter un tel framework.

**Comment by martialsomda** [comment]
ça marche

**Comment by roddet** [comment]
Je ferme ce point, nous allons d'abord concentrer nos efforts à finaliser qui est déjà fait. Nous réouvrirons ce point plus tard si nécessaire.
