### ISSUE TITLE
[Maintenabilite] Diminuer la proportion de code non documenter

### ISSUE THREAD

**Issue by martialsomda** [JCERTIFLab/jcertif-backend-2013#113]
Sonar affiche 8,3% de code documenté :-) => Diminuer la proportion de code non documenter

**Comment by roddet** [comment]
Il parait que quand c'est bien écrit, il n'y a pas besoin de commentaires :)

**Comment by martialsomda** [comment]
Effectivement...Ne commenter que le code ayant besoin d'être commenté (éviter de commenter les getter/setters :-) ) .
Sans même aller jusque là pour moi ça peut être bien codé mais dans la doc il y a aussi des liens vers d'autres classes @see, {@link} qui permettent de comprendre rapidement le design utilisé sans avoir forcément à mettre le nez dans l'algorithmie.

On peut néanmoins poser la question au groupe, au pire on saute dans sonar les erreurs sur la javadoc
