### ISSUE TITLE
[Service][Mobile] Créer un sponsor - ajout d'un numéro de version

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#116]
Lors de la création d'un sponsor, il faut valoriser le champ "version" en l'incrémentant

**Comment by martialsomda** [comment]
Rajout des attribut 'version' et 'deleted' aux objets du model JCertif
Les recherches sont faites sur les entités en base ayant l'attribut deleted à false.
Les création d'objet entrainent l'initialisation de l'attribut version  à 01 et retourne le nouveau numéro de version
Les mises à jour prennent en entrée la version, compararent la version en entrée avec la version de l'entité en base, incrémentent la version avant de persister les modifications, renvoient le nouveau numéro de version
Les suppressions prennent en entrée un numéro de version, entrainent une mise à jour de l'attribut deleted de l'entité en base
