### ISSUE TITLE
[Service] Créer un participant

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#13]
Requête : POST /participant/register   un objet Participant au format JSON.
Exemple : {email : 'lab@jcertif.org', lastname : 'Gates', fistname : 'Bill' }
Veuillez à valoriser tous les champs obligatoires.

Réponse :  HTTP 200

**Comment by bigoliver** [comment]
{
    email : "toto@yahoo.fr",
    password : "totopassword",
    title : "un title",
    lastname : "toto nom",
    firstname : "toto prenom",
    website : "toto website",
    city : "toto city",
    country : "toto country",
    company : "toto company",
    phone : "toto phone",
    photo : "toto photo url",
    biography : "toto biography"
}

Le participant à ajouter est contenu dans le corps de la requête

**Comment by bashizip** [comment]
@bigoliver  le format de ce JSON n'est pas valide.Je viens de corriger. voir prochain commit.
