### ISSUE TITLE
[Jenkins] Mettre dans Github le fichier application.conf utilisé pour l'environnement d'intégration

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#135]
Actuellement, l'application est déployée à chaque build Jenkins avec un fichier application.conf configuré pour l'environnement d'intégration (cloudbees).
Il s'agit ici de mettre ce fichier dans le contrôle de source et le build Jenkins l'utilisera pour le déploiement.
Cela permettra de mettre à jour ce fichier sans intervenir côté Jenkins.

**Comment by martialsomda** [comment]
Un fichier application-prod.conf a été crée sous git..coté jenkins, une option de déploiement a été rajoutée dans la commande de déploiement : -P config.resource=application-prod.conf
L'étape de copie ssh du fichier applicaton.conf d'intégration a été supprimée sur jenkins
