### ISSUE TITLE
[Warning compilation] Ne pas utiliser l'api interne du JDK

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#139]
En compilant le projet on peut voir le warning suivant : 

[warn] /home/roddet/dev/02_github/jcertiflab/jcertif-backend-2013/app/controllers/DefaultAuthenticator.java:12: warning: BASE64Decoder is internal proprietary API and may be removed in a future release
[warn] import sun.misc.BASE64Decoder;
[warn]                ^

**Comment by martialsomda** [comment]
ça marche..tout ce code sera retiré avec la suppression du serveur OAuth coté backend
