### ISSUE TITLE
[Service] Mettre à jour un participant

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#14]
Requête : POST /participant/update un objet Participant au format JSON.
Exemple : {email : 'lab@jcertif.org', lastname : 'Gates', fistname : 'Bill' }
Veuillez à valoriser tous les champs obligatoires. 

Réponse : HTTP 200

**Comment by bigoliver** [comment]
Toutes les infos sauf le mot de passe
