### ISSUE TITLE
[Mail] Envoyer un mail de confirmation au speaker lorsqu'une nouvelle session est créée

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#148]
Envoyer un mail de confirmation au speaker lorsqu'une nouvelle session est créé.

Exemple de wording de mail : https://github.com/JCERTIFLab/jcertif-backend-2012/blob/master/jcertif-services/src/main/resources/com/jcertif/service/mail/confirmProposition.st

**Comment by martialsomda** [comment]
Il faudrait modifier l'objet session pour le raccrocher à son créateur, et dans ce cas, si la session est modifiée par un admin, doit-on envoyer un email de modification au speaker? à l'admin?

**Comment by roddet** [comment]
Non pas besoin gérer le créateur.
1 session contient une liste de speakers.
Le mail n'est envoyé qu'aux speakers et uniquement à la création (pas en modification).

**Comment by bashizip** [comment]
Tout ça me rappelle les mails de play :)

**Comment by roddet** [comment]
@bashizip ça te rappelle une gueule de bois ou une détente sur une plage ?

**Comment by bashizip** [comment]
@Rossi : Un peu les deux a vrai dire :)

## 

Patrick Bashizi
Software Engineer
basizip@gmail.com
Kinshasa: (+243)995848935
Brazzaville :(+242)040033828
G+ : gplus.to/bashizip
Twitter : @bashizip

**Comment by martialsomda** [comment]
quelqu'un peut-il rajouter les logos des partenaires dans les images? ç

**Comment by martialsomda** [comment]
Oups..j'ai eu le clic rapide..ça permettra rajouter les logos dans les emails
