### ISSUE TITLE
[Mail] Destinataire en dur ?

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#150]
La constante fromEmail de la classe https://github.com/JCERTIFLab/jcertif-backend-2013/blob/master/app/models/notifiers/EmailNotification.java m'inquiete.

Il faudrait la supprimer et être sûr que nous utilisons les infos paramétrés.

**Comment by bashizip** [comment]
En effet . Je l'avais mise en dur de façon provisoire . Et puis c'est pas
cet émail qui devait être utilisé en production .

**Comment by roddet** [comment]
@bashizip Yes bien sûr ! Comme la première mise en prod arrive bientôt on va éviter d'avoir des surprises :)
