### ISSUE TITLE
[Service] Inscrire un participant à une session

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#17]
Requête :  POST    /participant/{email}/session/add/{idsession}        

Réponse : HTTP 200 + envoi d'un email au participant

**Comment by bigoliver** [comment]
Le client ne devrait-il pas se charger d'envoyer l'email au participant? Le backend ici ne servant qu'à enregistrer et supprimer les données, pas à faire du fonctionnel

**Comment by Bonbhel** [comment]
Le principe est vrai. Mais si on part aussi du principe que les clients sont interchangeables, ça oblige dans ce cas à revoir le mail et son format. Si on a le choix, je préférerais qu'on le garde comme un service fourni par le Backend.

**Comment by roddet** [comment]
Je confirme il faut gérer l'envoi du mail côté Backend pour unifier l'envoi du courrier quelque soit le client (application Android, site web, etc...)

Voici le courrier à réaliser :
![Print - Gmail - Confirmation Enregistrement Participation JCertif 2013_01](https://f.cloud.github.com/assets/1372183/191525/7f30d964-7f3b-11e2-9189-c0502875d051.png)

Attention, la phrase "Merci roddet@sqli.com roddet@sqli.com !" correspond à "Merci NOM PRENOM".

Tout en bas, il s'agit des logos des sponsors dont les urls sont à récupérés en base de données.

**Comment by Bonbhel** [comment]
Le lien qui propose de retourner vers la page de contact pourrait être problématique selon les client.
Ex : Si l'utilisateur s'inscrit via mon application IPhone ou du client Web Vaddin de @roddet, dois-je le renvoyer vers la page Web d'un autre client dans le mail de confirmation ?

**Comment by roddet** [comment]
Nous ne pouvons prédire si le client lira le mail depuis son mobile ou son desktop. En plus, il pourra consulter le mail plus tard soit avec son PC, soit avec son mobile quelque soit le média utilisé lors de l'inscription.
Donc je n'y vois pas de problématique particulière :)

**Comment by bigoliver** [comment]
Idée;
Pourquoi pas prévoir une interface qui permette à chaque client de demander
l'envoi d'un message particulier? C'est chaque client qui saura le contenu
du message. Ceci permet en outre au client de s'absoudre de la
problématique d'envoi de mail ( développement et gestion des librairies)
- Olivier M.

On 25 févr. 2013, at 13:31, Rossi Oddet notifications@github.com wrote:

Nous ne pouvons prédire si le client lira le mail depuis son mobile ou son
desktop. En plus, il pourra consulter le mail plus tard soit avec son PC,
soit avec son mobile quelque soit le média utilisé lors de l'inscription.
Donc je n'y vois pas de problématique particulière :)

—
Reply to this email directly or view it on
GitHubhttps://github.com/JCERTIFLab/jcertif-backend-2013/issues/17#issuecomment-14038764.

**Comment by roddet** [comment]
@bigoliver 
Yes pourquoi pas. Seulement, j'ai le sentiment que nous nous ajouterions de la complexité sans retour sur investissement.
Quelque soit le média d'inscription, la phrase n'a pas à changer. Elle reste la même.
En ce qui concerne l'url du lien, je ne vois pas trop qu'est-ce que l'on ferait de différent même si le participant s'inscrivait via son mobile. Il ne lit pas les mails via l'application JCertif mais vers son client mail habituel.

@Tous 
Je suis partant pour faire au plus simple, en tout cas, dans le cadre de cette tâche.
Ca serait déjà bien d'avoir un envoi de mail pour commencer et on affinera plus tard si besoin.
Nous créerons des tâches séparées et identifiées pour ces ajustements.
Qu'en pensez-vous ?

**Comment by Bonbhel** [comment]
Je vous laisse décider de la meilleure approche. Mais une chose est sûre
nous devons aller au plus simple pour l'instant avec des services stables
qui fonctionnent.

Merci,

Le 25 février 2013 07:59, Rossi Oddet notifications@github.com a écrit :

> @bigoliver https://github.com/bigoliver
> Yes pourquoi pas. Seulement, j'ai le sentiment que nous nous ajouterions
> de la complexité sans retour sur investissement.
> Quelque soit le média d'inscription, la phrase n'a pas à changer. Elle
> reste la même.
> En ce qui concerne l'url du lien, je ne vois pas trop qu'est-ce que l'on
> ferait de différent même si le participant s'inscrivait via son mobile. Il
> ne lit pas les mails via l'application JCertif mais vers son client mail
> habituel.
> 
> @Tous https://github.com/Tous
> Je suis partant pour faire au plus simple, en tout cas, dans le cadre de
> cette tâche.
> Ca serait déjà bien d'avoir un envoi de mail pour commencer et on affinera
> plus tard si besoin.
> Nous créerons des tâches séparées et identifiées pour ces ajustements.
> Qu'en pensez-vous ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JCERTIFLab/jcertif-backend-2013/issues/17#issuecomment-14039813.

## 

# 

Max Bonbhel - http://www.bonbhel.com/
Congo JUG Leader - http://www.congojug.com/
JCertif Founder and Managing Director  - http://www.jcertif.com
JUG-AFRICA President - http://java.net/projects/jug-africa/pages/Home

Java.net Blogger : http://weblogs.java.net/blog/bonbhel/
LinkedIn : http://ca.linkedin.com/in/bonbhel

Twitter : http://twitter.com/bonbhel
Google+ : gplus.to/maxbonbhel

**Comment by bigoliver** [comment]
Va pour le plus simple.
- Olivier M.

On 25 févr. 2013, at 14:12, Max Bonbhel notifications@github.com wrote:

Je vous laisse décider de la meilleure approche. Mais une chose est sûre
nous devons aller au plus simple pour l'instant avec des services stables
qui fonctionnent.

Merci,

Le 25 février 2013 07:59, Rossi Oddet notifications@github.com a écrit :

> @bigoliver https://github.com/bigoliver
> Yes pourquoi pas. Seulement, j'ai le sentiment que nous nous ajouterions
> de la complexité sans retour sur investissement.
> Quelque soit le média d'inscription, la phrase n'a pas à changer. Elle
> reste la même.
> En ce qui concerne l'url du lien, je ne vois pas trop qu'est-ce que l'on
> ferait de différent même si le participant s'inscrivait via son mobile.
> Il
> ne lit pas les mails via l'application JCertif mais vers son client mail
> habituel.
> 
> @Tous https://github.com/Tous
> Je suis partant pour faire au plus simple, en tout cas, dans le cadre de
> cette tâche.
> Ca serait déjà bien d'avoir un envoi de mail pour commencer et on
> affinera
> plus tard si besoin.
> Nous créerons des tâches séparées et identifiées pour ces ajustements.
> Qu'en pensez-vous ?
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/JCERTIFLab/jcertif-backend-2013/issues/17#issuecomment-14039813>.

## 

# 

Max Bonbhel - http://www.bonbhel.com/
Congo JUG Leader - http://www.congojug.com/
JCertif Founder and Managing Director - http://www.jcertif.com
JUG-AFRICA President - http://java.net/projects/jug-africa/pages/Home

Java.net Blogger : http://weblogs.java.net/blog/bonbhel/
LinkedIn : http://ca.linkedin.com/in/bonbhel

Twitter : http://twitter.com/bonbhel
Google+ : gplus.to/maxbonbhel

—
Reply to this email directly or view it on
GitHubhttps://github.com/JCERTIFLab/jcertif-backend-2013/issues/17#issuecomment-14040279.

**Comment by chrisbel** [comment]
c'est beau tout ce que je lis, je sens que le client Ext JS va s'amuser à
afficher des données jolies venant du Back-end hummmmm hâte de vite faire
un premier Test.

# ***Mes contacts

Roland Chrisbel
Développeur JAVA Édition Entreprise
Président JCertif FRANCE
Senior Manager JCertif International
Co-leader Congo Jug*
_Tél: + 33 7 61 61 71 56
mail: a.roland@chrisbel.net
twitter: http://twitter.com/ChrisbelM_
_idSkype: roland.chrisbel
www.jcertif.com
www.chrisbel.net
www.congojug.com_

# \* http://www.chrisbel.net

*

**Comment by bashizip** [comment]
D’accord avec @roddet ; faisons simple :)
