### ISSUE TITLE
[Service] Réinitialiser le mot de passe

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#20]
Requête : POST /participant/{email}/lostpassword       

Réponse : HTTP 200 et envoi d'un email avec le nouveau mot de passe

**Comment by bashizip** [comment]
Mot de passe réinitialisé, reste envoie de mail

**Comment by roddet** [comment]
![courrier_reinit_mot_passe](https://f.cloud.github.com/assets/1372183/201689/f615a558-80fa-11e2-9124-5dcd742533ac.PNG)

Voici un modèle du courrier à réaliser.

Pour la gestion des mots de passe, idéalement, il faut utiliser un cryptage type MD5.

Ainsi je verrai bien comme cinématique : 
1. Génération d'un String aléatoire
2. Cryptage du String + stockage en base de données
3. Envoie du mail avec le mot de passe non crypté

**Comment by bashizip** [comment]
En effet c'est le genre d'implémentation à  la quelle je pense aussi; sauf que je ne plus  la classer Mailer de play framework telle que décrite ici play.mvc.Mailer . Je suppose que c'est un problème de version mais j'ai rien trouvé dans la documentation qui indique ou ils l'ont déplacée !!
L'autre idée c'est d'utiliser carrément Apache commons. Qu'en dis-tu ?

**Comment by roddet** [comment]
Il faut faire au plus simple.
La priorité : utiliser le mécanisme fourni par Play. Attention a utiliser
les classes java et non scala.

Si ça ne fonctionne pas, tu peux utiliser la librairie de ton choix.

Envoyé depuis mon mobile,
Excusez la brièveté et les fautes :)

**Comment by bigoliver** [comment]
Le cryptage SHA + salage a été choisi dans la gestion des mots de passe
