### ISSUE TITLE
[Service] Supprimer une catégorie

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#42]
Requête : POST /ref/category/remove un objet au format JSON
Exemple : {label : 'HTML5'}

Réponse :HTTP 200 si OK

Ce service n'est accessible que si le client a les droits d'administration.

**Comment by bigoliver** [comment]
J'ai été plus vite que la musique...

**Comment by bashizip** [comment]
@bigoliver  c'est le moins qu'on puisse dire :))
