### ISSUE TITLE
[IHM] Formulaire de création d'un participant

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#53]
Il faudrait créer un formulaire qui permet de saisir toutes les informations d'un participant et de créer celui-ci en base de données.
Ce formulaire permettra de tester manuellement le service de création d'un participant.

**Comment by lordgodgiven** [comment]
@Mr fonctionnel binding Rossi,

Les formulaires sont à créer en html5?

Envoyer de mon androïd - Excusez la brieveté
Dieudonné NIEME

**Comment by roddet** [comment]
L'objectif de ce formulaire est de tester le service de création d'un participant. Il ne sera pas utilisé pour autre chose que du test.
Donc peut importe HTML5 ou pas, le plus important est de pouvoir faire un requête : 
POST /participant/register avec les informations d'un participant (https://github.com/JCERTIFLab/jcertif-backend-2013/wiki/Specifications).

Tu as le choix, amuses toi bien :)

Assignes toi la tâche si elle t'intéresse !

Tu peux t'inspirer de ce tutoriel pour créer le formulaire : http://www.playframework.com/documentation/2.1.0/JavaTodoList
La communauté est là pour compléter le reste !

**Comment by lordgodgiven** [comment]
Ok, message bien reçu

Envoyer de mon androïd - Excusez la brieveté
Dieudonné NIEME

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/b28cba26-f2bf-4435-b426-bdf4614bab41

## 

Ce message a été envoyé par Twitter à la demande d'utilisateurs de Twitter qui ont saisi votre adresse électronique pour vous inviter sur Twitter.
Se désinscrire : https://twitter.com/i/o?t=1&iid=b28b6a62e781475b9c7896dd53467b62&uid=0&c=IuVwbCB3dgEZkcmNY4pVMLmqNshWTBAL0wmfrdU1s%2FGd1t3B9pQqafx8jyzFEVW%2BnHVoV1tlshj96yEPECW1f9YEvyMOmh%2BtodHfaSYJ1NBCug7sbX5u0g%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/8a681c73-bb72-4c72-9c4b-cebd32ac309e

## 

Ce message a été envoyé par Twitter à la demande d'utilisateurs de Twitter qui ont saisi votre adresse électronique pour vous inviter sur Twitter.
Se désinscrire : https://twitter.com/i/o?t=1&iid=078d59a1e6f645a9bbcaac7b54fe3fc7&uid=0&c=IuVwbCB3dgEZkcmNY4pVMLmqNshWTBAL0wmfrdU1s%2FGd1t3B9pQqafx8jyzFEVW%2BnHVoV1tlshj96yEPECW1f9YEvyMOmh%2BtodHfaSYJ1NBCug7sbX5u0g%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/0ec7878c-05b8-413a-9785-8c8fd91892af

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Se désinscrire : https://twitter.com/i/o?t=1&iid=713ef646b654499e80c32fb6bc3daf8d&uid=0&c=IuVwbCB3dgEZkcmNY4pVMLmqNshWTBAL0wmfrdU1s%2FGd1t3B9pQqafx8jyzFEVW%2BnHVoV1tlshj96yEPECW1f9YEvyMOmh%2BtodHfaSYJ1NBCug7sbX5u0g%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/bd83cb12-d32e-49d8-ae0b-cece192a42cc

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Se désinscrire : https://twitter.com/i/o?t=1&iid=9fc884ca2dc14328aca1d598f9d09ecc&uid=0&c=IuVwbCB3dgEZkcmNY4pVMLmqNshWTBAL0wmfrdU1s%2FGd1t3B9pQqafx8jyzFEVW%2BnHVoV1tlshj96yEPECW1f9YEvyMOmh%2BtodHfaSYJ1NBCug7sbX5u0g%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
BOUBACAR Bachir,
Vous avez un nouvel abonné sur Twitter.

---

Dieudonné NIEME
@DNieme
Dieudonné NIEME, ingénieur en Réseaux et Télécoms
Congo Brazzaville

Suivre:
https://twitter.com/DNieme

## 

Si vous pensez que Dieudonné NIEME a un comportement abusif sur Twitter, vous pouvez signaler Dieudonné NIEME pour spam : https://twitter.com/i/redirect?url=https%3A%2F%2Ftwitter.com%2Fuser_spam_reports%2Fmboubacarbachir%2Freport%2FDNieme%3Ft%3D1%26sig%3D18561670407b6c4eafd3083643c73bb117035516%26iid%3D33b6079e7f1644b08c98bc82e2564fd5%26uid%3D2468953200%26accused%3DDNieme%26nid%3D23%2B465&t=1&sig=4adc757f153df80b13921e277e4fb4eaf27cc44b&iid=33b6079e7f1644b08c98bc82e2564fd5&uid=2468953200&nid=23+465

Mot de passe Twitter oublié ? Obtenez les instructions de réinitialisation :
https://twitter.com/account/resend_password

Vous pouvez également vous désabonner de ces emails ou modifier vos paramètres de notification :
https://twitter.com/i/u?t=1&sig=daab50d6863e1cf63c9552e8a2297e87ceed96b9&iid=33b6079e7f1644b08c98bc82e2564fd5&uid=2468953200&nid=23+26
https://twitter.com/settings/notifications

Besoin d'aide ?
https://support.twitter.com

Si vous avez reçu ce message par erreur et n'êtes pas inscrit sur Twitter, cliquez sur le lien ci-dessous :
https://twitter.com/account/not_my_account/mboubacarbachir/87347-HD889-139875

**Comment by bashizip** [comment]
This is a Spam !

Pas vrai ?
