### ISSUE TITLE
[IHM] Formulaire de création d'une session

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#54]
Créer un formulaire permettant de créer une session en base de données

**Comment by roddet** [comment]
Hello Séti,

Les formulaires que nous devons créer dans ce projet sont uniquement pour valider les services développés. Les IHM réellement utilisés seront développées dans les projets site web et back office.
Il faut que le code que nous écrivons pour réaliser ces formulaires soit bien distincts du code servant à implémenter les services. Ceci pour éviter d'avoir ces formulaires accessibles en production.

J'ai vu que tu as créé un formulaire accessible via l'appel http : GET     /session/new et que le code se situe controllers.SessionController.newSessionForm.

Je te propose 2 alternatives : 
1. Soit tu créés le formulaire en techno HTML/Javascript comme le formulaire de création de participant ou d'autres que tu as déjà développé. Cela permet de n'avoir aucun impact côté code java
2. Que tu crées un package controllers.test et tu créés un controleur dans ce package avec le même service. En url tu adaptes l'url en utilisant plutôt /test/session/new. Cela permettra de séparer les services de test des autres services.

Si tu as d'autres alternatives, n'hésites pas.

Qu'en penses-tu ?

**Comment by setico** [comment]
cool
