### ISSUE TITLE
[Service] Mettre à jour les informations d'un présentateur

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#64]
Créer un service REST :
Requête : POST /speaker/update un objet Speaker au format JSON.
Exemple : {email : 'lab@jcertif.org', lastname : 'Gates', fistname : 'Bill' }
Veuillez à valoriser tous les champs obligatoires. (voir spécification : https://github.com/JCERTIFLab/jcertif-backend-2013/wiki/Specifications)

Réponse : HTTP 200

Ce service ne doit être accessible pour un client ayant les droits d'administration

**Comment by bigoliver** [comment]
On ne met pas à jour le mot de passe du speaker. Il faut prévoir un ou deux services pour changer le mot de passe d'un présentateur ou réinitialiser son mot de passe

**Comment by roddet** [comment]
Yes bien vu, je vais créer les tâches dédiées !
