### ISSUE TITLE
[Validation] Création/Mise à jour d'un participant : vérifier que le champ title est valide

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#68]
Lors de la création ou la mise à jour d'un participant, il vaut veiller à ce que l'information contenue dans title fasse partie du référentiel "Liste des civilités".

**Comment by martialsomda** [comment]
"Liste des civilités" => Enum? ou il faut aussi un referentiel des civilité en base administrable?

**Comment by roddet** [comment]
Référentiel pour le fun :)

Envoyé depuis mon mobile,
Excusez la brièveté et les fautes :)
