### ISSUE TITLE
[Service] Speaker : Changer de mot de passe

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#70]
Requête : POST /speaker/{email}/changepassword Objet JSON : {oldpassword : 'blabvl', newpassword : 'jjj'}

Réponse : HTTP 200 + envoie d'un email de confirmation de changement de mot de passe

**Comment by bigoliver** [comment]
- envoi de mail :)

**Comment by roddet** [comment]
Pas nécessaire sauf si tu es un maniac de la sécurité :)
On garde le mail pour le service de réinitialisation plutôt... sauf si tu tiens au mail :)

**Comment by bigoliver** [comment]
Les présentateurs sont des personnes importantes pour JCertif, je pense qu'il faut, entre autres, leur montrer qu'il y a, en plus, un volet sécurité pris en compte.

**Comment by roddet** [comment]
Ok Go ! pour l'email

**Comment by bigoliver** [comment]
cool

**Comment by bashizip** [comment]
@Olivier : tu peux t'inspirer du code pour envoi de mail au participant ,c'est pratiquement  la même chose :)

**Comment by lordgodgiven** [comment]
En tous cas le terme robot code ne vous va plus, il faut trouver une autre
qualification, que penez-vous de termina-code?

Envoyer de mon androïd - Excusez la brieveté
Dieudonné NIEME

**Comment by bashizip** [comment]
Sinon je le fais des que possible :) Mais j'aurais aimé que tu te familiarise avec l'implementation que j'ai suggérée.

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/215a3d23-33b2-42d3-8f00-816dec44a674

## 

Ce message a été envoyé par Twitter à la demande d'utilisateurs de Twitter qui ont saisi votre adresse électronique pour vous inviter sur Twitter.
Se désinscrire : https://twitter.com/i/o?t=1&iid=559e6791c0c9408093dfdf17a2539dee&uid=0&c=IuVwbCB3dgERnSF%2F64fnJvlzBcUzovYHdXtKUaPEoPMMsvI7L6iEroHMZykCphrOonex6TXjduWyPpatKha8MoU9Bt69zwJGf%2BQ1wUJ11hurxFz3fP%2F9Jg%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/33e811ea-3d1c-4af4-a3e3-ea3865877cd0

## 

Ce message a été envoyé par Twitter à la demande d'utilisateurs de Twitter qui ont saisi votre adresse électronique pour vous inviter sur Twitter.
Se désinscrire : https://twitter.com/i/o?t=1&iid=63dbfa0ea04241c99d1dd418425b60be&uid=0&c=IuVwbCB3dgERnSF%2F64fnJvlzBcUzovYHdXtKUaPEoPMMsvI7L6iEroHMZykCphrOonex6TXjduWyPpatKha8MoU9Bt69zwJGf%2BQ1wUJ11hurxFz3fP%2F9Jg%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/585f7fbc-91b5-4a2a-9492-a24adbbb523a

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Se désinscrire : https://twitter.com/i/o?t=1&iid=0e6e11e50d0648d588dd519e105b3ccc&uid=0&c=IuVwbCB3dgERnSF%2F64fnJvlzBcUzovYHdXtKUaPEoPMMsvI7L6iEroHMZykCphrOonex6TXjduWyPpatKha8MoU9Bt69zwJGf%2BQ1wUJ11hurxFz3fP%2F9Jg%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/845946dd-1a14-46d3-9881-7ca223087d2a

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Se désinscrire : https://twitter.com/i/o?t=1&iid=b55d88e9b1554d11869aa3ab7935be5b&uid=0&c=IuVwbCB3dgERnSF%2F64fnJvlzBcUzovYHdXtKUaPEoPMMsvI7L6iEroHMZykCphrOonex6TXjduWyPpatKha8MoU9Bt69zwJGf%2BQ1wUJ11hurxFz3fP%2F9Jg%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com
