### ISSUE TITLE
[CONF] Migrer la configuration jcertifbackend.properties vers application.conf

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#80]
Afin d'unifier la configuration de l'application, nous allons utiliser un seul fichier : application.conf.

Il faudrait donc migrer toutes les propriétés du fichier jcertifbackend.properties dans application.conf.

Dans les noms des propriétés, il faudra enlever le préfixe jcertifbackend.
Exemple : 
database.name=jcertif au lieu jcertifbackend.database.name=jcertif

**Comment by bashizip** [comment]
Bien ! Rossi.
Penser aussi a modifier le compte jcertifDebugUser vers un compte final.
