### ISSUE TITLE
[REFACTORING] Déplacer le répertoire notifiers dans models

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#82]

**Comment by bashizip** [comment]
@Rossi
Notifiers ne serait pas plus proche de la business logic que du model ?

**Comment by roddet** [comment]
@bashizip 
En fait tu as 3 briques dans une application Play : 
- Le contrôleur : réception des requêtes, utilisation des modèles puis retour de la vue
- Le modèle : entité, mise à jour bdd, ...
- La vue : comme son nom l'indique

On doit pouvoir architecturer nos applications avec ces 3 briques et à l'intérieur de chaque brique on s'organise comme on veut.

Il ne faut pas voir le "model" comme l'objet métier mais objet métier + traitements liés.
En fait, avec Play nous ne sommes pas dans une application 3-tiers avec une couche business.
On pourrait placer l'envoie d'email dans le contrôleur ou le modèle mais j'ai fait le choix du modèle dans l'optique où si l'on veut faire du transactionnel (envoie d'email que si la sauvegarde à totalement réussie), l'endroit où ça sera possible sera le modèle.
J'espère que ça t'apporte quelques éléments du pourquoi de ce choix. C'est plus philosophique que technique :)
