### ISSUE TITLE
Liste des services accessible uniquement en droit d'admin

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#85]
Actuellement, lorsque la sécurité est activée, tous les services nécessitent le droit d'administration.
Il faudrait rendre la liste des services nécessitant le droit d'admin paramétrable (code ou en dehors).
Par exemple, via une annotation comme @Secure sur les services sécurisés ou via un moyen de compléter le fichier Route pour dire si un service est sécurisé ou pas.

**Comment by martialsomda** [comment]
Voici la liste des services qui ont besoin d'authentificattion :
./app/controllers/CategoryController.java:    newCategory
./app/controllers/CategoryController.java:    removeCategory
./app/controllers/CiviliteController.java:      addCivilite
./app/controllers/CiviliteController.java:      removeCivilite
./app/controllers/ParticipantController.java:   updateParticipant
./app/controllers/ParticipantController.java:   getParticipant
./app/controllers/ParticipantController.java:   listParticipant
./app/controllers/ParticipantController.java:   removeParticipant
./app/controllers/ParticipantController.java:   inscrireParticipantSession
./app/controllers/ParticipantController.java:   desinscrireParticipantSession
./app/controllers/ParticipantController.java:   listParticipantSession
./app/controllers/SessionController.java:    newSession
./app/controllers/SessionController.java:    removeSession
./app/controllers/SessionController.java:    updateSession
./app/controllers/SessionStatusController.java:    addSessionStatus
./app/controllers/SessionStatusController.java:    removeSessionStatus
./app/controllers/SpeakerController.java:    updateSpeaker
./app/controllers/SpeakerController.java:    removeSpeaker
./app/controllers/SponsorController.java:    updateSponsor
./app/controllers/SponsorController.java:    addSponsor
./app/controllers/SponsorController.java:    removeSponsor
./app/controllers/SponsorLevelController.java:  addSponsorLevel
./app/controllers/SponsorLevelController.java:  removeSponsorLevel

Manque-t-il des services? y en a-t-il en trop?

**Comment by roddet** [comment]
Petite question : 
J'ai vu que tu as mis en place l'annotation @Authenticated(Admin.class), est-il possible d'avoir plutôt une annotation sur préciser la classe (par exemple @Secure) ?

Pour la liste, je pourrai faire une passe pour les services et poser les jolies annotations partout où il le faut.

Dans ta liste, voici les services en trop : 
./app/controllers/ParticipantController.java: updateParticipant
./app/controllers/ParticipantController.java: getParticipant
./app/controllers/ParticipantController.java: listParticipant
./app/controllers/ParticipantController.java: inscrireParticipantSession
./app/controllers/ParticipantController.java: desinscrireParticipantSession
./app/controllers/ParticipantController.java: listParticipantSession
./app/controllers/SessionController.java: newSession
./app/controllers/SessionController.java: removeSession
./app/controllers/SessionController.java: updateSession
./app/controllers/SpeakerController.java: updateSpeaker

Le principe est le suivant : Ne nécessitent les droits d'administration uniquement les services que n'offrent pas le site web traditionnel même avec un utilisateur connecté. Typiquement, un utilisateur connecté pourra gérer ses infos (updateParticipant, getParticipant,listParticipant), il pourra s'inscrire à une session (inscrireParticipantSession) etc...
Mais il ne pourra pas créer un nouveau niveau de sponsoring etc...

Je pense que tu peux me laisser m'occuper de cette partie. Une fois que tu auras fini de traiter le point sur l'annotation, je ferai une passe sur toute l'application et je mettrai l'annotation partout où c'est indispensable. Le plus important, est d'avoir un levier facile à mettre en oeuvre pour l'activer sur un service ou le désactiver.

**Comment by martialsomda** [comment]
2 annotations :
@Admin
@Connected

Elles permettent d'annoter les services ayant besoin d'un droit admin et les services nécessitant d'être connecté..Je n'était pas sur pr cette dernière annotation par ce qu'on se retrouverai sûrement dans le même cas que le backoffice pr le site web jcertif..obligation de fusionner..l'authentification utilisateur devrait sûrement être géré uniquement sur le site jcertif et on pourai mettre en place un une authentification oauth pr les différentes appli habilitées a accéder aux services du backend..Désolé si c'est pas très claire, je suis connecté depuis mon tel, on en reparlera..

**Comment by bigoliver** [comment]
Ouais, j'ai pas tout compris :)

Le 14 avril 2013 12:42, Martial SOMDA notifications@github.com a écrit :

> 2 annotations :
> @Admin
> @Connected https://github.com/Connected
> 
> Elles permettent d'annoter les services ayant besoin d'un droit admin et
> les services nécessitant d'être connecté..Je n'était pas sur pr cette
> dernière annotation par ce qu'on se retrouverai sûrement dans le même cas
> que le backoffice pr le site web jcertif..obligation de
> fusionner..l'authentification utilisateur devrait sûrement être géré
> uniquement sur le site jcertif et on pourai mettre en place un une
> authentification oauth pr les différentes appli habilitées a accéder aux
> services du backend..Désolé si c'est pas très claire, je suis connecté
> depuis mon tel, on en reparlera..
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JCERTIFLab/jcertif-backend-2013/issues/85#issuecomment-16349117
> .

## 
- Olivier

**Comment by roddet** [comment]
Je suis Ok pour les 2 annotations. Quoique j'aurai préféré @Authenticated à la place de @Connected. A mes yeux, on peut être connecté sans être authentifié :)
Entre le site web et le backend, on se servira de oAuth (avec un tiers de confiance), je vais créer une tâche distincte pour ce travail à faire.
En gros, les requêtes qui nécessitent l'authentification vont être faits avec un token. Le serveur va regarder dans son cache (à durée limitée) si ce token existe et s'il n'existe pas il fait une requête auprès du tiers de confiance pour valider le token et si tout est Ok, le serveur met se token en cache puis répond positivement.

**Comment by martialsomda** [comment]
lol Désolé Olivier, ce que je disais tout simplement c'est @Admin sert a annoter les services necessitant des droits admin et @Connected pour annoter les services nécessitant d'être authentifié.

Le problème c'est qu'il y a à mon sens 2 type d'authentifications : 
- Une authentification utilisateur
- Une authentification de l'appli utilisant JCertif Backend (une espece de API key)

Vu que le mécanisme d'authentification qu'on utilise avec play se repose sur la session (cookie signé) on ne peut pas avoir d'intermédiaire entre le navigateur de l'utilisateur et les services du backend. d'où la fusion du backend et du backoffice pour que les droit admin puissent marcher.
Tu m’arrêtes @Rossi si j'ai loupé un truc..

Si les services du backend devaient aussi gérer l'authentification utilisateur ça nous forcerait de la même façon que le backoffice à fusionner le site web Jcertif avec le backend.

L'alternative c'est de laisser au site web JCertif la responsabilité de gérer dans sa session le fait qu'un utilisateur soit authentifié ou pas puis de générer au près d'un tier de confiance un jeton de validité pour cet utilisateur (hash de l'API key + email par exemple). Ce jeton sera transmit aux services du backend pour toutes les requêtes à venir.

Coté backend pour les services nécessitant une authentification utilisateur une vérification de la validité du jeton en entrée sera faite au près du tièr de confiance. puis le jeton sera mis en cache.
Tu m’arrêtes @Rossi si j'ai encore loupé un truc..

**Comment by roddet** [comment]
@martialsomda Je suis Ok avec ce que tu dis.

Cela me fait penser qu'avec la présence du tiers de confiance, on n'est plus obligé d'héberger le backoffice sur le même domaine.

Quoi qu'il en soit il nous faut distingué les 2 cas : mode admin et mode authentifié, donc oui 2 annotations.

On va commencer à atteindre les limites de l'exercice son véritable IHM pour tester, il faut que j'accelère le lancement des développements du site web. Si tout va bien, ce week-end on va commencer à avoir des choses :)
