### ISSUE TITLE
[Service] Proposer une session

### ISSUE THREAD

**Issue by roddet** [JCERTIFLab/jcertif-backend-2013#9]
Requête : POST /session/new    un objet Session au format JSON (voir spécifications)
Exemple : {title : 'Blu blu', summary : 'Bla bla'}
Veuillez à valoriser tous les champs obligatoires. 

Réponse : HTTP 200

**Comment by bigoliver** [comment]
Exemple de Session à proposer

{
 id : "Session id",
 title : "Session title",
 summary : "Session summary",
 description : "Session Description",
 status : "Session Status",
 keyword : "Session keyword",
 category : ["category 1", "category 2"],
 start : "12/02/2013 10:22",
 end : "16/02/2013 10:23",
 speakers : ["Speaker id 1", "Speaker id 2"]
}

En plus des contrôles de présence, il y a un contrôle sur le format de la date et un autre sur le fait d'avoir une date de début antérieure à la date de fin de la session
